import Main from "layouts/Main";
import type { NextPage } from "next";
import Head from "next/head";
const Home: NextPage = () => {
  return (
    <Main>
      <Head>
        <title>HOME - ENSAM CASA</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
    </Main>
  );
};

export default Home;
