# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    working-directory: src/server

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: src/admin/package-lock.json
      - run: echo this is the admin action
      - run: |
          cd ../admin 
          npm install
          npm run build
          npm run lint-check --if-present
          npm run format-check --if-present
          cd ../server
          ls
      - run: npm install
      - run: npm run lint-check --if-present
      - run: npm run format-check --if-present
      - run: |
          cd ../../
          git push origin `git subtree split --prefix src/server master`:admin --force
