# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ADMIN CI

on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [master]

defaults:
  run:
    working-directory: src/admin/server

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: src/admin/client/package-lock.json
      - run: npm install
      - run: npm run lint-check --if-present
      - run: npm run format-check --if-present
      - run: |
          cd ../client
          npm install
          npm run build:linux
          npm run lint-check --if-present
          npm run format-check --if-present
          cd ../server
          cd ../../../
          git config --global user.email "karim2jihad@gmail.com"
          git config --global user.name "Karim G."
          git add .
          git commit --allow-empty -m "github actions"
          git push origin `git subtree split --prefix src/admin/server master`:admin --force
