name: Version Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Commit report
        run: |
          git push origin `git subtree split --prefix src/client master`:heroku --force
          git push origin `git subtree split --prefix src/admin master`:admin-dashboard --force
